# Test playbook for the bertvv.rh-base role with role variables set.
#
# The SSH keys for the admin user are stored in tests/sshkey. Check SSH login with e.g.
#
#   ssh -i sshkey/admin_key -p 2222 admin@127.0.0.1
#
# The port number is the forwarded port on the VirtualBox NAT interface that Vagrant also uses to
# connect to the VM.
---

- hosts: all
  become: true
  pre_tasks:
    - name: Include distro-specific variables
      include_vars: "vars-{{ ansible_distribution }}.yml"
  vars:
    rhbase_ssh_user: admin
    rhbase_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4MHsjCu/wAKQkwMvMdQuFMPPBXROtz8qA8ayD/opYNkvd7kIp9yv+thl5PNV5Ds/EObDeepKuKEyH1Td54YrQ0VOyKuAl9b6LrXG5ZZg6jzlwPvuWV1YT4AasMfg5Wb60C+lfT/wC52fi3Ls3QUnpj1YV6fcKgnjjjMOlQt+lS1dhMSy7Q2/qLkhhMsTi6jgiG0VbXRXYwedEN7I8wUAguyLJPwDHrEGfZv4WqjvVOx/zM+CEXMCJLY+sbUUlQBVFxfq9pQ8hoVd5sK3/BIuphp7zZFbXZAPy7PBnkmfhuUxROvgnoLzdERF/uSqFTxV4DtBXw3JLvmhd7QxzcU5J admin@example.com'
    rhbase_firewall_allow_services:
      - http
      - https
    rhbase_firewall_allow_ports:
      - 8080/tcp
      - 53/udp
    rhbase_firewall_interfaces:
      - enp0s3
      - enp0s8
    rhbase_start_services:
      - sshd
    rhbase_user_groups:
      - juniors
      - seniors
    rhbase_users:
      - name: admin
        comment: Administrator
        groups:
          - seniors
        password: '$6$sPS1h6qt/hYpaChG$zgyO0DPn4k/NaTouvtiEgFXK9obiPQOOYZq4.HnLf8XuVL4hznmQxvCXiY4/y5cGUBrxJWG3frfP/lOWABu2p0'
      - name: joe
        comment: 'Joe Smith'
        groups:
          - juniors
        password: '$6$WIFkXf07Kn3kALDp$fHbqRKztuufS895easdTVAWyVeqVrWcdVMH9jztH2kTOsuCswKFpIijeR/c4QjM6g1ASHjDbeTrwcgEl4Rafk.'
      - name: jane
    rhbase_repo_gpgcheck: false
    rhbase_repo_installonly_limit: 2
    rhbase_install_packages:
      - vim-enhanced
      - bind-utils
    rhbase_dynamic_motd: true
    rhbase_hosts_entry: true
    rhbase_update: false
    rhbase_selinux_booleans:
      - httpd_can_network_connect_db
      - collectd_tcp_network_connect
    rhbase_automatic_updates: true
    rhbase_updates_type: security
    rhbase_updates_debuglevel: 10
    rhbase_updates_apply: true
    rhbase_updates_download: true
    rhbase_yum_cron_hourly_install_updates: true
    rhbase_yum_cron_hourly_update_level: security
    rhbase_updates_email_from: admin
    rhbase_selinux_state: 'enforcing'
  roles:
    - rh-base
